Enhanced ops script
gardener/etcd-wrapper pull request #18
Opened 2023-12-01 06:36 UTC by unmarshall

**How to categorize this PR?**

/area dev-productivity
/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Introduces a new ops script which will now print all paths and popularly used etcd commands used by operators. Essentially a one stop shot for all things that an operator typically needs/executes.

**Which issue(s) this PR fixes**:
Fixes #17 

**Special notes for your reviewer**:

**Release note**:

```other operator
ops/print-etcd-cert-paths.sh has been removed and is now replaced with ops/print-etcd-cheatsheet.sh
```

2023-12-01 11:25 UTC, seshachalam-yv requested changes

2023-12-01 11:25 UTC, seshachalam-yv commented on ops/print-etcd-cheatsheet.sh
> +#!/usr/bin/env bash
license. headers are missing

2023-12-01 11:34 UTC, seshachalam-yv commented on ops/print-etcd-cheatsheet.sh
> +backup_restore_pid=$(get_backup_restore_process_id)
Verify that both `wrapper_pid` and `backup_restore_pid` are valid before proceeding

2023-12-01 12:11 UTC, aaronfern commented
Thanks for the review @seshachalam-yv!
I've addressed your review comments. PTAL

2023-12-01 14:24 UTC, shreyas-s-rao commented on ops/Dockerfile
@aaronfern can you also please update the alpine image version in a separate PR?

2023-12-04 07:39 UTC, shreyas-s-rao approved these changes
/lgtm

2023-12-05 06:12 UTC, seshachalam-yv approved these changes
lgtm

2023-12-06 04:49 UTC, merged